### ISSUE TITLE
Transparent background in the Color chooser view

### ISSUE THREAD

**Issue by krzema12** [Unia/gcolor3#19]
Steps to reproduce the problem on my system:

1. Open `gcolor3` through the console. The background looks as is should.
2. Open **Saved colors** tab.
3. Go back to **Color chooser** tab. The window has no solid background - it looks like this:

![transparentbackground](https://cloud.githubusercontent.com/assets/3110813/4873695/351c290e-6220-11e4-94df-b1df6f4791b1.png)

Some info about my system:
* Ubuntu 14.04 LTS 64-bit
* graphics: Chromium
* running on Oracle VM VirtualBox virtual machine

**Comment by Unia** [comment]
Can you try again now? I have rewritten Gcolor3 to a great extent, so something might have fixed this :)

**Comment by krzema12** [comment]
I have a problem compiling the newest version. After calling `./autogen.sh` (BTW, you should update it in the readme, there's still `./autogen`) and `make` I'm getting:

    make  all-recursive
    make[1]: Entering directory `/home/piotr/Desktop/gcolor3'
    Making all in src
    make[2]: Entering directory `/home/piotr/Desktop/gcolor3/src'
    make  all-am
    make[3]: Entering directory `/home/piotr/Desktop/gcolor3/src'
      CC       gcolor3-main.o
    In file included from main.c:31:0:
    gcolor3-application.h:51:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
     Gcolor3Application *gcolor3_application_new ();
     ^
    main.c:45:2: error: ISO C forbids initialization between function pointer and ‘void *’     [-Werror=pedantic]
      { "version", 'v', G_OPTION_FLAG_NO_ARG, G_OPTION_ARG_CALLBACK,     _print_version_and_exit, N_("Show the application's version"), NULL },
      ^
    main.c:45:2: error: (near initialization for ‘options[0].arg_data’) [-Werror=pedantic]
    cc1: all warnings being treated as errors
    make[3]: *** [gcolor3-main.o] Error 1
    make[3]: Leaving directory `/home/piotr/Desktop/gcolor3/src'
    make[2]: *** [all] Error 2
    make[2]: Leaving directory `/home/piotr/Desktop/gcolor3/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/home/piotr/Desktop/gcolor3'
    make: *** [all] Error 2

Can you try to fresh-clone the repo and see if it also occurs? Maybe it's because I have some older version of gcc?

**Comment by Unia** [comment]
Are you sure you have the latest master? That issue arose yesterday but should be fixed now, see [this commit](https://github.com/Unia/gcolor3/commit/b8d8f866d87b4bee6536dd0f5bfe03b831720b7c).

Otherwise, check if you have some other flags overriding gcolor3's and adding `pedantic`.

**Comment by krzema12** [comment]
Right, I must have had a bit older commit.
After I pulled the newest one, I was getting another error:

      CC       gcolor3-gcolor3-application.o
    gcolor3-application.c: In function ‘gcolor3_application_init_accelerators’:
    gcolor3-application.c:113:3: error: implicit declaration of function     ‘gtk_application_set_accels_for_action’ [-Werror=implicit-function-declaration]
       gtk_application_set_accels_for_action (application, it[0], &it[1]);
       ^
    cc1: all warnings being treated as errors

Instead of looking for the option that makes my GCC treat all warnings as errors, I checked what's exactly wrong with the code. It turned out that you've used `gcolor3_application_init_accelerators(...)` which is [available since GTK+ 3.12](https://developer.gnome.org/gtk3/stable/GtkApplication.html#gtk-application-set-accels-for-action). My version was 3.10.

After updating GTK+ to 3.12, I finally managed to build the project. But when trying to run `gcolor3`, I'm getting

    gcolor3: symbol lookup error: gcolor3: undefined symbol: gtk_application_set_accels_for_action

I'll try to solve it in a couple of days. Do you have any idea what might be wrong? Is it possible that I've updated the dev version and the runtime is still old?

**Comment by Unia** [comment]
> It turned out that you've used `gcolor3_application_init_accelerators(...)` which is [available since GTK+ 3.12](https://developer.gnome.org/gtk3/stable/GtkApplication.html#gtk-application-set-accels-for-action). My version was 3.10.

Whoops! Sorry, I will update the minimum version required.

> Is it possible that I've updated the dev version and the runtime is still old?

That is quite possible. Assuming you are still using Ubuntu, updating only `libgtk-3-dev` is indeed not enough. You will also have to update `libgtk-3-0`.

**Comment by krzema12** [comment]
I finally managed to compile and run gcolor3 - it works :)

(some update has just broken my installation of Ubuntu, so I won't be able to check anything in the following time...)

**Comment by Unia** [comment]
Great! I'm going to close this issue then. Feel free to reopen or create a new issue if the issue returns.
